### ISSUE TITLE
Runtime Error: Number of Default Vertex Uniforms exceeds HW limits.

### ISSUE THREAD

**Issue by Mardanshahi** [johnWRS/LearnOpenGLTextRenderingImprovement#1]
I have runtime error when I run your code in my computer. I am not sure how this error happens however it seems when Shader compiler reaches the line 9 in text.vs which is "uniform mat4 transforms[400];" this error occurs. I compiled and examined the code in a Windows device with a Intel HD Graphics 530 GPU which is updated to the latest driver. 

ERROR::PROGRAM_LINKING_ERROR of type: PROGRAM
Number of Default Vertex Uniforms exceeds HW limits.

**Comment by johnWRS** [comment]
Hi there,

I discuss this in the video but different graphics hardware will allow differing array sizes. The larger an array, the more letters can be rendered in one draw call, improving performance. This leads to a relationship where your individual graphics card will limit how large the array can be but you want it as large as possible for your hardware to maximize performance.

I haven't found a reliable way to query the GPU hardware and ascertain the limit (there are queries but the numbers don't seem to be reliable and potentially differ with different manufacturers). If I find one, I'll update the code and in the short term I may add a comment around this.

To solve your error just try smaller values than 400 (my game uses 100). Be sure to also change the const unsigned int ARRAY_LIMIT to match that value.
